---
apiVersion: v2
name: mbelt
description: Mbelt helm chart
version: 1.0.1
appVersion: 1.0.0
maintainers:
- name: Artem Nurmatov
  email: artem.n@p2p.org
dependencies:
- name: rabbitmq
  repository: "file://rabbitmq"
  version: 1.2.0
  alias: rabbitmq
  condition: rabbitmq.enabled
