---
environment: mbelt3-prod
chain: kusama
role: staking-processor
replicas: 0
limits: {cpu: 450m, memory: 4096Mi}
requests: {cpu: 350m, memory: 4096Mi}
image: {repository: eu.gcr.io/substrate-infra/mbelt3_preloader, tag: 4ac9f3c46dc0b60f27b92e0710134d705db82b72}
port: 3000
metrics:
  enabled: true
vault:
  role: "mbelt"
  secret: "secret/mbelt/mbelt3_kusama"
additional_args:
  - "--max_old_space_size=4096"
env:
  substrate_uri: ws://substrate-ws-proxy-prod.kusama.svc.cluster.local:9944
  log_level: info
  network_id: 2
  mode: STAKING_PROCESSOR
  network: kusama
ingress:
  enabled: true
  class: nginx-external
  host: mbelt3-kusama-staking-processor.polka.p2p.world
  tls:
    cluster_issuer: cloudflare-prod
    secret: mbelt3-kusama-staking-processor-polka-p2p-world
    ssl_redirect: true
tolerations:
  - key: cloud.google.com/gke-spot
    operator: Equal
    value: "true"
    effect: NoSchedule

