{{ if and (eq .Values.role "preloader") .Values.migrations.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: {{ template "app.migrate" $ }}-
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  ttlSecondsAfterFinished: 86400  # 24h
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        env: {{ .Values.environment }}
        chain: {{ .Values.chain }}
        role: {{ .Values.role }}-migrations
        {{- include "app.commonLabels" . | nindent 8 }}
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/role: {{ .Values.vault.role | quote }}
        vault.hashicorp.com/agent-inject-secret-config: {{ .Values.vault.secret | quote }}
        vault.hashicorp.com/agent-inject-template-config: |
          {{"{{"}} with secret {{ .Values.vault.secret | quote }} {{"-}}"}}
          {{"{{"}}- range $key, $value := .Data.data {{"}}"}}
          export {{"{{"}} $key {{"}}"}}={{"{{"}} $value {{"}}"}}
          {{"{{"}}- end {{"}}"}}
          {{"{{-"}} end {{"}}"}}
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ template "app.fullname" $ }}
      containers:
      - name: migrations
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
        command:
        - 'sh'
        - '-c'
        - |
          source /vault/secrets/config;
          npm run migrations:up
        {{- with .Values.env }}
        env:
        - { name: SUBSTRATE_URI, value: {{ quote .substrate_uri }} }
        - { name: LOG_LEVEL,     value: {{ quote .log_level }} }
        - { name: NETWORK_ID,    value: {{ quote .network_id }} }
        - { name: MODE,          value: {{ quote .mode }} }
        - { name: NETWORK,       value: {{ quote .network }} }
        - { name: SUBSCRIBE,     value: {{ quote .subscribe }} }
        - { name: PRELOAD,       value: {{ quote .preload }} }
        {{- end }}
        - { name: REST_API_PORT, value: {{ quote .Values.port }} }
        - { name: BASIC_AUTH,    value: "false" }
        - { name: NODE_ENV,      value: "production" }
{{ end }}
