---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.fullname" $ }}
  labels:
    app: {{ .Chart.Name }}
    env: {{ .Values.environment }}
    chain: {{ .Values.chain }}
    role: {{ .Values.role }}
    {{- include "app.commonLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      env: {{ .Values.environment }}
      chain: {{ .Values.chain }}
      role: {{ .Values.role }}
      {{- include "app.commonLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        env: {{ .Values.environment }}
        chain: {{ .Values.chain }}
        role: {{ .Values.role }}
        {{- include "app.commonLabels" . | nindent 8 }}
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/role: {{ .Values.vault.role | quote }}
        vault.hashicorp.com/agent-inject-secret-config: {{ .Values.vault.secret | quote }}
        vault.hashicorp.com/agent-inject-template-config: |
          {{"{{"}} with secret {{ .Values.vault.secret | quote }} {{"-}}"}}
          {{"{{"}}- range $key, $value := .Data.data {{"}}"}}
          export {{"{{"}} $key {{"}}"}}={{"{{"}} $value {{"}}"}}
          {{"{{"}}- end {{"}}"}}
          {{"{{-"}} end {{"}}"}}
    spec:
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      serviceAccountName: {{ template "app.fullname" $ }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      containers:
      - name: streamer
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports: [ containerPort: {{ .Values.port }} ]
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
        command:
        - sh
        - -c
        - |
          sleep 86400
        {{- with .Values.env }}
        env:

        - { name: RESTART_BLOCKS_URI,   value: {{ quote .restart_blocks_uri }} }
        - { name: RESTART_ERAS_URI,     value: {{ quote .restart_eras_uri }} }
        - { name: RESTART_ROUNDS_URI,   value: {{ quote .restart_rounds_uri }} }
        - { name: RESTART_BALANCES_URI, value: {{ quote .restart_balances_uri }} }
        - { name: SUBSTRATE_URI, value: {{ quote .substrate_uri }} }
        - { name: LOG_LEVEL,     value: {{ quote .log_level }} }
        - { name: NETWORK_ID,    value: {{ quote .network_id }} }
        - { name: MODE,          value: {{ quote .mode }} }
        - { name: NETWORK,       value: {{ quote .network }} }
        - { name: SUBSCRIBE,     value: {{ quote .subscribe }} }
        - { name: PRELOAD,       value: {{ quote .preload }} }
        {{- end }}
        - { name: REST_API_PORT, value: {{ quote .Values.port }} }
        - { name: BASIC_AUTH,    value: "false" }
        - { name: NODE_ENV,      value: "production" }
        resources:
          limits: { cpu: {{ .Values.limits.cpu }}, memory: {{ .Values.limits.memory }} }
          requests: { cpu: {{ .Values.requests.cpu }}, memory: {{ .Values.requests.memory }} }
