---
environment: mbelt3-prod
chain: vara
role: staking-processor
replicas: 1
limits: {cpu: 450m, memory: 4096Mi}
requests: {cpu: 350m, memory: 4096Mi}
vault:
  role: "mbelt"
  secret: "secret/mbelt/mbelt3_vara"
additional_args:
  - "--max_old_space_size=4096"
env:
  substrate_uri: ws://vara-archive-node.gear.svc.cluster.local:9944
  log_level: info
  network_id: 137
  mode: STAKING_PROCESSOR
  network: vara
ingress:
  enabled: true
  host: mbelt3-vara-staking-processor.polka.p2p.world
  tls:
    secret: mbelt3-vara-staking-processor-polka-p2p-world
